kind: pipeline
type: docker
name: backend-ci

steps:
  - name: install-dependencies
    image: node:22
    commands:
      - cd backend
      - npm ci
      - npx prisma generate

  - name: run-unit-tests
    image: node:22
    commands:
      - cd backend
      - npm run test

  - name: build-project
    image: node:22
    commands:
      - cd backend
      - npm run build


---
kind: pipeline
type: docker
name: frontend-ci

steps:
  - name: install-dependencies
    image: node:22
    commands:
      - cd frontend
      - npm ci

  - name: build-project
    image: node:22
    commands:
      - cd frontend
      - npm run build


---
kind: pipeline
type: docker
name: deploy-ci

depends_on:
  - backend-ci
  - frontend-ci

steps:
  - name: deploy-to-vercel
    image: node:22
    environment:
      VERCEL_TOKEN:
        from_secret: vercel_token
      VERCEL_ORG_ID:
        from_secret: vercel_org_id
      VERCEL_PROJECT_ID:
        from_secret: vercel_project_id
    commands:
      - echo "Iniciando processo de deploy para a Vercel..."
      - |
        if [ -z "$VERCEL_TOKEN" ]; then
          echo "ERRO FATAL: Segredos da Vercel ausentes. Não é possível realizar o deploy."
          exit 1
        else
          npm install -g vercel
          vercel pull --yes --environment=production --token=$VERCEL_TOKEN
          vercel build --prod --token=$VERCEL_TOKEN
          vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
        fi
