kind: pipeline
type: docker
name: backend-ci

steps:
  - name: install-dependencies
    image: node:22
    commands:
      - cd backend
      - npm ci
      - npx prisma generate

  - name: run-unit-tests
    image: node:22
    commands:
      - cd backend
      - npm run test

  - name: build-project
    image: node:22
    commands:
      - cd backend
      - npm run build

  - name: deploy-backend
    image: alpine
    commands:
      - echo "Realizando etapas adicionais de entrega/deploy do Back-end..."

---
kind: pipeline
type: docker
name: frontend-ci

steps:
  - name: install-dependencies
    image: node:22
    commands:
      - cd frontend
      - npm ci

  - name: build-project
    image: node:22
    commands:
      - cd frontend
      - npm run build

  - name: deploy-frontend
    image: alpine
    commands:
      - echo "Realizando etapas adicionais de publicação/deploy do Front-end..."
